---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
        args: [--assume-in-merge]
      - id: check-added-large-files
      - id: check-yaml
      - id: trailing-whitespace
        exclude_types:
          - markdown
      - id: end-of-file-fixer

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.105.0
    hooks:
      # - id: terraform_checkov
      - id: terraform_fmt
      - id: terraform_tflint
      # - id: terraform_trivy
      - id: terraform_validate
        args:
          - --tf-init-args=-upgrade
          - --hook-config=--retry-once-with-cleanup=true
      # - id: terrascan
      # - id: tfupdate
